CREATE DATABASE IF NOT EXISTS alx_book_store;

-
USE alx_book_store;


CREATE TABLE authors (
  AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(215) NOT NULL
);


CREATE TABLE books (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT,
  PRICE DOUBLE NOT NULL,
  PUBLICATION_DATE DATE,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);


CREATE TABLE customers (
  CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215) NOT NULL UNIQUE,
  ADDRESS TEXT
);


CREATE TABLE orders (
  ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT,
  ORDER_DATE DATE NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);


CREATE TABLE order_details (
  ORDERDETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID INT,
  BOOK_ID INT,
  QUANTITY DOUBLE NOT NULL,
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);